### ISSUE TITLE
Display # of sessions

### ISSUE THREAD

**Issue by Laghzaoui** [dalibo/powa-web#17]
Hello,
the Powa-web UI can display # of sessions par snapshot ?

`select count(*) FROM pg_stat_activity;`

Thanks for your replay

**Comment by rjuju** [comment]
Hello,

This has been requested before, see https://github.com/dalibo/powa/issues/40 and more recently https://groups.google.com/forum/?hl=fr#!topic/powa-users/rL_dLV1IPKA

As I said there, getting the number of concurrent sessions is provided by a lot of other monitoring tool and is IMHO less needed than the things we plan to implement in the next release, so it's not a high priority for PoWA right now. We still keep in mind that multiple people want this!

**Comment by Laghzaoui** [comment]
Thanks for all :)
