### ISSUE TITLE
Unhandled Exception in resolve_quals

### ISSUE THREAD

**Issue by NeuralGlue** [dalibo/powa-web#30]
I receive the following error in my pows-web console when I select Optimize this Database.

Note that I have had this working in the past on this database, and optimize query works correctly on other databases on the same server.

    [E 170525 15:38:31 web:1548] Uncaught exception GET /metrics/database/amidb_sce/wizard/?from=2017-05-24+15%3A28%3A55-0700&to=2017-05-25+15%3A28%3A55-0700 (10.10.11.6)
    HTTPServerRequest(protocol='http', host='xxxx:8888', method='GET', uri='/metrics/database/amidb_sce/wizard/?from=2017-05-24+15%3A28%3A55-0700&to=2017-05-25+15%3A28%3A55-0700', version='HTTP/1.1', remote_ip='10.10.11.6', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'xxxx:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://xxxx:8888/database/amidb_sce/overview/?to=2017-05-25T15%3A28%3A55-07%3A00&from=2017-05-24T15%3A28%3A55-07%3A00', 'Cookie': '_flashes="2|1:0|10:1495751899|8:_flashes|4:Ti4=|961d5284786c899b8a0dcc4d2a99445e2a15a8d6ec15b1d3dcf948fe4c91e77d"; password="2|1:0|10:1495643496|8:password|20:d2FsdGVyMTFnYXJiYWdl|4920b2b163976c387870c9645893b75440ce81ada42b171d0117930996a11f34"; server="2|1:0|10:1495643496|6:server|8:bWFpbg==|03a3ddfd161d257062e1b90282d90c100a6858c5c0ef3c7409ccb07a86a26790"; username="2|1:0|10:1495643496|8:username|8:YW1pZGI=|b98f86474d74963f207d3cb5eaee310da120f48a493448e3e747ea6763527b37"'})
    Traceback (most recent call last):

          File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
            result = method(*self.path_args, **self.path_kwargs)

          File "/home/cyoung/powa-web/powa/dashboards.py", line 87, in get
            data = self.post_process(data, **url_params)

          File "/home/cyoung/powa-web/powa/wizard.py", line 110, in post_process
            data["data"] = resolve_quals(conn, data["data"])

          File "/home/cyoung/powa-web/powa/sql/__init__.py", line 243, in resolve_quals
            attname = attnames["%s.%s" % (v["relid"], v["attnum"])]

    KeyError: u'19683.2'

Any ideas on how I should try to debug the issue?

**Comment by rjuju** [comment]
That's weird, both keys should be integer.

Could you print v in resolve_quals? Something like
```diff
diff --git a/powa/sql/__init__.py b/powa/sql/__init__.py
index 0f7a3b9..44d9728 100644
--- a/powa/sql/__init__.py
+++ b/powa/sql/__init__.py
@@ -240,6 +240,7 @@ def resolve_quals(conn, quallist, attribute="quals"):
         if not isinstance(values, list):
             values = [values]
         for v in values:
+            print(v)
             attname = attnames["%s.%s" % (v["relid"], v["attnum"])]
             if newqual.relname is not None:
                 if newqual.relname != attname['relname']:
```

**Comment by NeuralGlue** [comment]
The issue is associated with the date/time frame selected at the top of the page. If I remove the arguments from the url ($from=...&to=...), the query performs normally. However, if I run the optimize over a specific period, I receive an exception.

Using the code:

```
diff --git a/powa/sql/__init__.py b/powa/sql/__init__.py
index 0f7a3b9..a73d10a 100644
--- a/powa/sql/__init__.py
+++ b/powa/sql/__init__.py
@@ -240,7 +240,9 @@ def resolve_quals(conn, quallist, attribute="quals"):
         if not isinstance(values, list):
             values = [values]
         for v in values:
+            print('v => ', v)
+            print('attnums =>' , attnames)
            attname = attnames["%s.%s" % (v["relid"], v["attnum"])]
             if newqual.relname is not None:
                 if newqual.relname != attname['relname']:
                     raise ValueError("All individual qual parts should be on the "

```

The output, if I include the $from=...&to= in the URL, is:

('v => ', {u'opno': u'96', u'eval_type': u'i', u'relid': u'20431', u'attnum': 2})
('attnums =>', {u'17242.7': {u'attname': u'cust_bin', u'table_liverows': 1882, u'nspname': u'public', u'most_common_values': u'{110101,150101,170105,120101,130101,070101,080101,190105,060101,180105,140101,100101,090101,050101,020101,040101,010101,030101,160101,100201,050201,130201,150201,200103,010201,070201,140201,060201,160105,030201,040301,080201,090201,010301,030301,040201,120201,180205,190103,010401,020201,020301,050301,110201,190205,200203,200106,160201,170205,060301,090301,020401,030401,140301,160205,070401,050401,030501,040401,070301,160301,170305,200104,200206,010501,080301,110301,200102,200204}', u'null_frac': 0.124336, u'relname': u'customers', u'n_distinct': 101}, u'17258.7': {u'attname': u'years_pre', u'table_liverows': 36590675, u'nspname': u'public', u'most_common_values': u'{0,1,2,-1,3,-2,-3}', u'null_frac': 0, u'relname': u'meter_part', u'n_distinct': 7}, u'20627.10': {u'attname': u'day_bin', u'table_liverows': 1570294, u'nspname': u'public', u'most_common_values': u'{010,100,020,200,110,300,011,030,101,400,021,111,201,000,301,040,500,031,401,120,001,210,600,050,501,041,121,601,051,211,060,700,061,701,070,130,800,310,131,311,801,071}', u'null_frac': 2.66667e-05, u'relname': u'daybins', u'n_distinct': 42}, u'17242.8': {u'attname': u'holdout', u'table_liverows': 1882, u'nspname': u'public', u'most_common_values': u'{0,1}', u'null_frac': 0, u'relname': u'customers', u'n_distinct': 2}, u'20627.2': {u'attname': u'wid', u'table_liverows': 1570294, u'nspname': u'public', u'most_common_values': u'{140089,140101,140245,140261,140599,140873,142311,142673,143525,143725,144031,144283,145493,145607,145747,146025,146077,146347,146621,146715,147005,147378,147676,148729,148737,149449,149717,149893,149987,150854,152277,152522,152897,152929,153793,155153,155251,156949,157674,158331,158809,159547,160198,160654,160908,161516,162243,163143,163209,163229,163299,163405,163563,165562,165978,166052,166232,166750,167158,167660,167918,168784,168820,169314,169384,169614,169870,170034,170176,170324,170626,171182,171316,172166,173324,173774,174080,174220,174318,174798,174946,175608,175906,176964,177126,177674,178055,178320,178930,179416,179800,179892,180486,180592,181724,182734,182820,182852,183456,184718,184738,184926,186314,186854,187124,187156,187310,187898,189662,190320,190348,190810,192896,193030,193334,193510,194593,194631,195337,195663,195667,195691,196033,196051,196655,197420,197498,197558,198252,198380,199228,199544,199726,201070,201368,201458,203152,203284,204098,204576,204650,205364,205552,205682,206046,206696,208042,208558,209355,209437,209707,209791,210269,210285,210371,210387,210539,212537,212771,212807,213041,213505,214489,214699,214817,214873,216883,217283,217374,218002,218210,218244,218412,218514,219503,219535,219559,219641,220213,220425,220535,220871,221107,221193,221855,221941,222185,222786,222900,223040,223432,224044,224256,224440,224644,225128,226202,226346,226856,227044,227272,228472,229044,229666,231062,231662,231674,231866,232054,232278,232430,232458,1240872,1240978,1242182,1243106,1243842,1243892,1244085,1245756,1247147,1247325,1247473,1247808,1248376,1249667,1249678,1250208,1250650,1252082,1252410,1252557,1252709,1252729,1252877,1253259,1253412,1253560,1254288,1254433,1254548,1254736,1255134,1255809,1255841,1256497,1256767,1257000,1257047,1258602,1259918,1259976,1260070,1260282,1260610,1260968,1261860,1263056,1263661,1264311,1264445,1264574,1264717,1264721,1264823,1265211,1265243,1265893,1265991,1266142,1266285,1267286,1267402,1268124,1268882,1269179,1269251,1269308,1269660,1269720,1270199,1270233,1270895,1271051,1271523,1271741,1272142,1272180,1272544,1272984,1273185,1273306,1273470,1273742,1275288,1275542,1275656,1276780,1277214,1277578,1278728,1279080,1279284,1279398,1279826,1281483,1281623,1282526,1282936,1283302,1284086,1284410,1284674,1285172,1285470,1286446,1287088,1287336,1288201,1288599,1289058,1290418,1291196,1291666,1292648,1292764,1292906,1293729,1294019,1294308,1294326,1295765,1296731,1296771,1297261,1297403,1297567,1298379,1298465,1298558,1299235,1299989,1300087,1300209,1300447,1300929,1301242,1301686,1302368,1302556,1303550,1303868,1304265,1304375,1304429,1304588,1304928,1305406,1305576,1307199,1307731,1307815,1307865,1307893,1308127,1308673,1308849,1308885,1309089,1310946,1311044,1312011,1312312,1312867,1313610,1313952,1314238,1315223,1315253,1315273,1316774,1318105,1318493,1319566,1319856,1320166,1320508,1321096,1321862,1321880,1322304,1322398,1322963,1323141,1323945,1323973,1324691,1325221,1325480,1325865,1325936,1326557,1326787,1327107,1328075,1329144,1329880,1330269,1330383,1332553,1332629,1475974,1476092,1477712,1478518,1478950,1479710,1479840,1481168,1482021,1482525,1482801,1483487,1484353,1484871,1485149,1485623,1485705,1485811,1486265,1486431,1488077,1488343,1488681,1489621,1490155,1490855,1491299,1491531,1492001,1492009,1492213,1493479,1494009,1494041,1494675,1495223,1495601,1495687,1495847,1495867,1496619,1497356,1497626,1497900,1498786,1499628,1499640,1500130,1500150,1500198,1500296,1501326,1503748,1503882,1504230,1504690,1504854,1505102,1505572,1506194,1506446,1506528,1507182,1507508,1507700,1508182,1508366,1508524,1508980,1510019,1511278,1512270,1512446,1513290,1513434,1513642,1513834,1514501,1514721,1515697,1516141,1516439,1517952,1518000,1518474,1518646,1519458,1519500,1519862}', u'null_frac': 2.66667e-05, u'relname': u'daybins', u'n_distinct': -0.503641}, u'17258.9': {u'attname': u'wid', u'table_liverows': 36590675, u'nspname': u'public', u'most_common_values': u'{5439960,5455804,5473362,5474268,5479895,2251924,5420884,5458185,5479215,5480252,19239261,2212699,5170817,5196008,5243134,5399602,5401853,5408067,5416543,5435671,5439486,5439882,5439902,5451187,5452376,5453977,5454219,5455714,5458105,5461600,5465441,5471665,5472127,5474590,5475665,5478137,5478477,5479489,5479808,5483860,1250282,1298913,2181412,2194795,2196564,2203931,2221835,2230964,2233444,2234808,2239041,2243440,2270175,2272887,2697911,4061978,4086542,5169155,5172130,5178320,5186196,5190465,5193171,5226475,5226655,5234662,5235830,5237372,5240142,5396444,5396648,5397373,5399678,5400322,5400735,5402421,5404835,5406997,5409776,5411976,5413587,5413779,5415582,5417465,5417945,5420088,5421747,5423359,5423833,5424801,5424972,5425290,5425780,5428009,5428613,5430750,5432803,5433593,5433789,5434625,5435409,5436276,5436631,5437059,5437173,5437815,5439780,5440630,5441507,5442695,5444405,5444518,5445071,5445812,5447090,5448087,5448279,5448573,5449055,5450400,5450608,5451325,5451592,5452612,5453306,5453626,5453658,5454235,5454291,5455538,5456069,5457042,5457231,5459011,5459513,5461604,5462294,5463070,5463112,5464744,5464748,5468913,5469745,5469761,5470645,5471416,5472802,5473719,5474254,5474414,5474500,5474704,5475204,5475380,5476465,5476519,5477171,5477445,5477843,5478199,5478281,5478668,5478783,5479019,5479427,5479993,5480334,5480597,5481582,5481778,5482272,5482884,5485027,5485039,5485399,5486175,5487337,19224058,19262125,1291892,1315501,1316073,1518152,1547360,2183071,2184518,2184672,2185127,2188742,2192887,2199594,2202943,2206956,2212661,2214631,2215913,2218210,2218754,2224976,2227883,2227909,2228623,2228881,2230420,2235504,2238665,2242950,2243108,2244410,2247364,2249144,2251181,2252920,2254778,2254998,2261730,2263862,2264282,2264798,2264836,2264985,2267959,2268717,2271193,2272385,2272829,2664605,2670929,2681152,2691262,2697977,2702760,2718520,3419523,4046201,4058786,4073215,4077918,4078302,4078455,4078617,4082907,4090268,4099683,4103544,4107059,4111238,4114004,5165961,5186628,5186703,5187021,5195454,5195576,5197397,5198601,5198817,5199984,5203199,5205445,5206874,5208148,5208643,5209445,5209719,5210825,5211630,5211640,5213134,5215326,5218677,5219631,5219677,5219995,5221381,5222569,5223322,5227451,5230679,5230949,5232810,5233342,5236779,5237690,5238602,5240746,5241045,5244343,5244556,5246630,5246686,5247672,5248816,5251148,5251316,5252942,5395869,5395911,5395999,5396416,5396506,5397248,5397805,5398271,5398327,5398463,5398757,5399297,5399320,5399823,5399938,5400184,5400507,5401417,5401935,5402041,5402453,5402551,5402609,5403051,5403548,5403748,5403777,5404029,5404350,5404558,5405062,5405642,5405874,5406755,5408001,5408055,5408091,5408405,5408823,5408964,5409524,5409548,5409732,5409854,5409928,5411043,5412106,5412480,5412708,5412790,5412888,5413143,5413527,5413567,5413629,5414434,5414488,5414786,5415010,5415175,5415472,5416133,5417127,5418455,5418475,5419272,5419280,5419520,5419748,5419826,5420296,5420382,5420464,5420720,5420958,5421097,5421567,5422037,5422222,5422316,5422577,5422581,5422751,5423057,5423119,5423233,5423503,5423923,5424009,5424053,5424347,5425074,5425148,5425242,5425752,5425916,5426136,5426431,5426781,5427211,5427931,5428306,5428360,5428986,5429028,5430178,5430404,5430498,5430672,5431028,5431883,5432275,5432345,5432717,5432903,5432957,5433381,5433487,5433529,5433835,5434086,5434210,5434267,5434341,5434585,5434769,5435001,5435667,5435773,5435781,5435785,5436063,5436887,5436899,5437007,5437043,5437193,5437603,5437757,5438109,5438557,5438583,5438617,5438801,5438977,5439556,5439792,5439922,5440412,5440796,5441116,5441312,5441609,5441731,5441845,5442653,5443793,5443821,5444385,5445001,5445027,5445079,5445589,5445619,5445627,5446171,5446566,5446958,5447870,5448063,5448139,5450255,5450624,5450676,5450690,5450746,5451722,5451772,5451878,5452102,5452322,5453012,5453250,5453827,5453933,5454447,5454840,5454848,5455370,5455506,5456007,5456175,5456513,5456665,5456709,5456767,5456984,5457345,5457409,5457507,5457565,5457925,5458679,5458921}', u'null_frac': 0.0343133, u'relname': u'meter_part', u'n_distinct': 236605}})
[E 170526 13:51:02 web:1548] Uncaught exception GET /metrics/database/amidb_sce/wizard/?from=2017-05-25+13%3A47%3A39-0700&to=2017-05-26+13%3A47%3A39-0700 (10.10.11.6)
    HTTPServerRequest(protocol='http', host='amidb.evergreenecon.com:8888', method='GET', uri='/metrics/database/amidb_sce/wizard/?from=2017-05-25+13%3A47%3A39-0700&to=2017-05-26+13%3A47%3A39-0700', version='HTTP/1.1', remote_ip='10.10.11.6', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'amidb.evergreenecon.com:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://amidb.evergreenecon.com:8888/database/amidb_sce/overview/?from=2017-05-25T13%3A47%3A39-07%3A00&to=2017-05-26T13%3A47%3A39-07%3A00', 'Cookie': '_flashes="2|1:0|10:1495831659|8:_flashes|4:Ti4=|cd488e36095904e514e803ebf8ddcd70858b0451a6667ffcb8f71400f262c706"; password="2|1:0|10:1495643496|8:password|20:d2FsdGVyMTFnYXJiYWdl|4920b2b163976c387870c9645893b75440ce81ada42b171d0117930996a11f34"; server="2|1:0|10:1495643496|6:server|8:bWFpbg==|03a3ddfd161d257062e1b90282d90c100a6858c5c0ef3c7409ccb07a86a26790"; username="2|1:0|10:1495643496|8:username|8:YW1pZGI=|b98f86474d74963f207d3cb5eaee310da120f48a493448e3e747ea6763527b37"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/cyoung/powa-web/powa/dashboards.py", line 87, in get
        data = self.post_process(data, **url_params)
      File "/home/cyoung/powa-web/powa/wizard.py", line 110, in post_process
        data["data"] = resolve_quals(conn, data["data"])
      File "/home/cyoung/powa-web/powa/sql/__init__.py", line 245, in resolve_quals
        attname = attnames["%s.%s" % (v["relid"], v["attnum"])]
    KeyError: u'20431.2'
[E 170526 13:51:02 web:1971] 500 GET /metrics/database/amidb_sce/wizard/?from=2017-05-25+13%3A47%3A39-0700&to=2017-05-26+13%3A47%3A39-0700 (10.10.11.6) 89.78ms

**Comment by NeuralGlue** [comment]
I made the change:

'''
diff --git a/powa/sql/__init__.py b/powa/sql/__init__.py
index 0f7a3b9..845048d 100644
--- a/powa/sql/__init__.py
+++ b/powa/sql/__init__.py
@@ -240,7 +240,10 @@ def resolve_quals(conn, quallist, attribute="quals"):
         if not isinstance(values, list):
             values = [values]
         for v in values:
+           print('v => ', v)
+           print('Search Key', "%s.%s" % (v["relid"], v["attnum"]))
+           print('attnums =>' , attnames)
            attname = attnames["%s.%s" % (v["relid"], v["attnum"])]
             if newqual.relname is not None:
                 if newqual.relname != attname['relname']:
                     raise ValueError("All individual qual parts should be on the "


This issue appears to be dependent on specific queries being in the date range selected. 

When a problematic query is within the range:

('v => ', {u'opno': u'96', u'eval_type': u'i', u'relid': u'20431', u'attnum': 2})
('Search Key', u'20431.2')
('attnums =>', {u'17242.7': {u'attname': u'cust_bin', u'table_liverows': 1882, u'nspname': u'public', u'most_common_values': u'{070107,080107,050107,100106,040107,060107,030107,110106,010107,020107,120108,090107,090106,060207,030207,040207,080207,010207,110108,020307,050207,100206,010307,070207,120103,020207,030307,010407,090207,110206,120203,090206,040307,050307,120208,020407,100306,030407,040407,080307,060307,020507,110208,010507,070307,120101,050507,060407,070407,090307,120105}', u'null_frac': 0.124336, u'relname': u'customers', u'n_distinct': 73}, u'17258.7': {u'attname': u'years_pre', u'table_liverows': 36590675, u'nspname': u'public', u'most_common_values': u'{0,1,2,-1,3,-2,-3}', u'null_frac': 0, u'relname': u'meter_part', u'n_distinct': 7}, u'20700.10': {u'attname': u'day_bin', u'table_liverows': 1570294, u'nspname': u'public', u'most_common_values': u'{010,100,020,200,110,300,011,030,101,400,021,201,111,000,301,040,500,031,401,120,001,600,210,501,050,041,121,601,051,211,060,700,061,701,070,310,130,800,131,311,071,801}', u'null_frac': 4e-05, u'relname': u'daybins', u'n_distinct': 42}, u'17242.8': {u'attname': u'holdout', u'table_liverows': 1882, u'nspname': u'public', u'most_common_values': u'{0,1}', u'null_frac': 0, u'relname': u'customers', u'n_distinct': 2}, u'20700.2': {u'attname': u'wid', u'table_liverows': 1570294, u'nspname': u'public', u'most_common_values': u'{140685,141813,141825,141951,142179,142193,142539,142555,143377,144019,144659,144697,144721,144745,145199,145293,147017,147127,148579,149367,149473,149567,150093,151471,152615,152661,152955,153583,153611,155161,155799,157788,158113,158407,158821,159535,159691,159759,160704,161146,161362,161382,161727,162318,162406,163707,164896,165754,165908,166210,167550,168266,169034,169050,169536,169548,169760,170674,171022,171312,171472,171872,172393,172421,172656,173276,173970,174906,174914,175660,176236,177134,177146,177412,178334,178440,179260,179436,179652,179946,180028,181087,181127,181488,183272,183472,183828,183930,184204,184334,184530,185670,185956,186074,186266,186294,186638,186714,187572,187614,188046,188418,189646,191104,191490,192410,192584,193160,194121,194423,195215,195727,195793,195859,195985,196945,197193,197608,197672,198776,199062,199518,199552,200924,202238,202862,203632,204298,204826,204858,205180,205708,205802,206614,206884,207296,207654,208320,208512,208876,209037,209523,210441,210869,211177,211283,212259,212387,212717,213203,213301,214461,214531,215115,215287,215735,216083,216159,217394,217892,218518,218836,219861,220197,220461,221335,221455,222424,222582,223020,223420,224072,224154,224570,225280,225680,226138,226464,226586,226594,226896,227020,227268,227526,227598,227896,228056,228980,229400,229420,229746,229800,229844,230318,230604,230890,230996,231502,231584,231600,231678,231984,232078,232364,1241440,1241802,1242096,1242680,1242938,1243240,1243472,1243554,1243558,1243972,1244062,1244207,1244638,1244655,1244762,1244900,1245170,1245870,1245960,1246018,1246090,1246788,1248605,1249641,1249874,1249910,1250376,1251506,1251953,1252929,1253026,1253596,1254978,1256477,1257671,1258019,1258071,1258316,1258972,1260128,1260172,1260540,1261050,1261664,1262436,1263258,1263422,1263470,1264425,1264745,1265137,1265709,1267230,1267674,1267858,1267896,1268450,1268856,1268860,1269332,1269767,1270007,1270219,1270227,1270941,1271211,1272340,1273418,1274090,1274722,1275742,1275774,1276140,1277460,1277498,1277648,1277656,1278328,1278680,1278770,1278774,1278814,1279238,1280550,1281188,1282344,1282862,1283176,1283212,1283442,1283610,1283634,1284512,1284610,1284992,1285368,1285722,1285730,1285878,1286008,1286152,1286794,1287552,1288435,1288484,1288492,1288553,1288880,1288896,1289106,1289115,1289217,1290149,1290492,1291106,1291128,1291286,1291556,1291939,1291993,1292170,1293208,1293298,1293334,1293669,1293837,1294033,1295007,1295031,1295207,1296735,1297135,1297457,1297673,1297705,1297967,1298127,1298253,1298538,1299187,1299553,1299559,1299940,1301116,1302058,1302210,1302594,1303328,1303728,1304209,1304568,1305180,1305638,1305642,1306138,1306403,1307453,1307559,1307599,1307661,1307999,1308191,1308629,1309053,1309397,1309937,1309967,1310043,1311024,1311044,1311894,1311991,1312422,1312798,1313106,1314226,1314316,1314409,1314745,1315441,1315599,1316023,1316314,1316354,1316730,1317574,1317608,1318289,1318324,1318642,1319038,1319222,1319242,1319798,1320460,1320528,1320782,1321068,1322262,1322540,1322865,1323323,1324661,1325824,1325964,1326078,1326309,1327013,1327249,1327404,1327515,1327747,1328029,1328899,1329270,1329782,1330033,1330519,1330809,1331245,1331323,1331773,1331919,1331997,1332511,1332539,1332565,1332671,1476058,1476120,1477030,1477966,1478640,1481146,1481384,1483611,1483827,1484685,1485195,1485231,1485807,1486725,1487563,1487755,1487967,1488281,1488391,1489939,1490687,1491013,1493413,1494071,1494821,1495119,1495819,1495871,1496373,1497202,1497892,1498060,1498088,1498361,1498467,1498507,1499504,1499828,1500284,1500322,1500938,1501048,1501306,1501722,1501770,1502086,1502866,1503012,1503282,1503642,1504282,1504564,1504658,1505402,1505610,1506172,1506900,1507740,1507838,1508084,1508664,1508892,1509619,1509855,1510506,1510546,1510918,1511086}', u'null_frac': 4e-05, u'relname': u'daybins', u'n_distinct': -0.504523}, u'17258.9': {u'attname': u'wid', u'table_liverows': 36590675, u'nspname': u'public', u'most_common_values': u'{5439960,5455804,5473362,5474268,5479895,2251924,5420884,5458185,5479215,5480252,19239261,2212699,5170817,5196008,5243134,5399602,5401853,5408067,5416543,5435671,5439486,5439882,5439902,5451187,5452376,5453977,5454219,5455714,5458105,5461600,5465441,5471665,5472127,5474590,5475665,5478137,5478477,5479489,5479808,5483860,1250282,1298913,2181412,2194795,2196564,2203931,2221835,2230964,2233444,2234808,2239041,2243440,2270175,2272887,2697911,4061978,4086542,5169155,5172130,5178320,5186196,5190465,5193171,5226475,5226655,5234662,5235830,5237372,5240142,5396444,5396648,5397373,5399678,5400322,5400735,5402421,5404835,5406997,5409776,5411976,5413587,5413779,5415582,5417465,5417945,5420088,5421747,5423359,5423833,5424801,5424972,5425290,5425780,5428009,5428613,5430750,5432803,5433593,5433789,5434625,5435409,5436276,5436631,5437059,5437173,5437815,5439780,5440630,5441507,5442695,5444405,5444518,5445071,5445812,5447090,5448087,5448279,5448573,5449055,5450400,5450608,5451325,5451592,5452612,5453306,5453626,5453658,5454235,5454291,5455538,5456069,5457042,5457231,5459011,5459513,5461604,5462294,5463070,5463112,5464744,5464748,5468913,5469745,5469761,5470645,5471416,5472802,5473719,5474254,5474414,5474500,5474704,5475204,5475380,5476465,5476519,5477171,5477445,5477843,5478199,5478281,5478668,5478783,5479019,5479427,5479993,5480334,5480597,5481582,5481778,5482272,5482884,5485027,5485039,5485399,5486175,5487337,19224058,19262125,1291892,1315501,1316073,1518152,1547360,2183071,2184518,2184672,2185127,2188742,2192887,2199594,2202943,2206956,2212661,2214631,2215913,2218210,2218754,2224976,2227883,2227909,2228623,2228881,2230420,2235504,2238665,2242950,2243108,2244410,2247364,2249144,2251181,2252920,2254778,2254998,2261730,2263862,2264282,2264798,2264836,2264985,2267959,2268717,2271193,2272385,2272829,2664605,2670929,2681152,2691262,2697977,2702760,2718520,3419523,4046201,4058786,4073215,4077918,4078302,4078455,4078617,4082907,4090268,4099683,4103544,4107059,4111238,4114004,5165961,5186628,5186703,5187021,5195454,5195576,5197397,5198601,5198817,5199984,5203199,5205445,5206874,5208148,5208643,5209445,5209719,5210825,5211630,5211640,5213134,5215326,5218677,5219631,5219677,5219995,5221381,5222569,5223322,5227451,5230679,5230949,5232810,5233342,5236779,5237690,5238602,5240746,5241045,5244343,5244556,5246630,5246686,5247672,5248816,5251148,5251316,5252942,5395869,5395911,5395999,5396416,5396506,5397248,5397805,5398271,5398327,5398463,5398757,5399297,5399320,5399823,5399938,5400184,5400507,5401417,5401935,5402041,5402453,5402551,5402609,5403051,5403548,5403748,5403777,5404029,5404350,5404558,5405062,5405642,5405874,5406755,5408001,5408055,5408091,5408405,5408823,5408964,5409524,5409548,5409732,5409854,5409928,5411043,5412106,5412480,5412708,5412790,5412888,5413143,5413527,5413567,5413629,5414434,5414488,5414786,5415010,5415175,5415472,5416133,5417127,5418455,5418475,5419272,5419280,5419520,5419748,5419826,5420296,5420382,5420464,5420720,5420958,5421097,5421567,5422037,5422222,5422316,5422577,5422581,5422751,5423057,5423119,5423233,5423503,5423923,5424009,5424053,5424347,5425074,5425148,5425242,5425752,5425916,5426136,5426431,5426781,5427211,5427931,5428306,5428360,5428986,5429028,5430178,5430404,5430498,5430672,5431028,5431883,5432275,5432345,5432717,5432903,5432957,5433381,5433487,5433529,5433835,5434086,5434210,5434267,5434341,5434585,5434769,5435001,5435667,5435773,5435781,5435785,5436063,5436887,5436899,5437007,5437043,5437193,5437603,5437757,5438109,5438557,5438583,5438617,5438801,5438977,5439556,5439792,5439922,5440412,5440796,5441116,5441312,5441609,5441731,5441845,5442653,5443793,5443821,5444385,5445001,5445027,5445079,5445589,5445619,5445627,5446171,5446566,5446958,5447870,5448063,5448139,5450255,5450624,5450676,5450690,5450746,5451722,5451772,5451878,5452102,5452322,5453012,5453250,5453827,5453933,5454447,5454840,5454848,5455370,5455506,5456007,5456175,5456513,5456665,5456709,5456767,5456984,5457345,5457409,5457507,5457565,5457925,5458679,5458921}', u'null_frac': 0.0343133, u'relname': u'meter_part', u'n_distinct': 236605}})
[E 170526 14:30:22 web:1548] Uncaught exception GET /metrics/database/amidb_sce/wizard/?from=2017-05-25+14%3A23%3A02-0700&to=2017-05-26+14%3A23%3A02-0700 (10.10.11.6)
    HTTPServerRequest(protocol='http', host='x.x.x:8888', method='GET', uri='/metrics/database/amidb_sce/wizard/?from=2017-05-25+14%3A23%3A02-0700&to=2017-05-26+14%3A23%3A02-0700', version='HTTP/1.1', remote_ip='10.10.11.6', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': 'x.x.x:8888', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.1 Safari/603.1.30', 'Dnt': '1', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://x.x.x:8888/database/amidb_sce/overview/?from=2017-05-25T14%3A23%3A02-07%3A00&to=2017-05-26T14%3A23%3A02-07%3A00', 'Cookie': '_flashes="2|1:0|10:1495834217|8:_flashes|4:Ti4=|cb1f96ad6b25c5821cbf8021e36886173c8d6613b60dd09a82b07bf0621739a3"; password="2|1:0|10:1495643496|8:password|20:d2FsdGVyMTFnYXJiYWdl|4920b2b163976c387870c9645893b75440ce81ada42b171d0117930996a11f34"; server="2|1:0|10:1495643496|6:server|8:bWFpbg==|03a3ddfd161d257062e1b90282d90c100a6858c5c0ef3c7409ccb07a86a26790"; username="2|1:0|10:1495643496|8:username|8:YW1pZGI=|b98f86474d74963f207d3cb5eaee310da120f48a493448e3e747ea6763527b37"'})
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/cyoung/powa-web/powa/dashboards.py", line 87, in get
        data = self.post_process(data, **url_params)
      File "/home/cyoung/powa-web/powa/wizard.py", line 110, in post_process
        data["data"] = resolve_quals(conn, data["data"])
      File "/home/cyoung/powa-web/powa/sql/__init__.py", line 246, in resolve_quals
        attname = attnames["%s.%s" % (v["relid"], v["attnum"])]
    KeyError: u'20431.2'

**Comment by rjuju** [comment]
Ok.

What does this query returns on the amidb_sce database?

```sql
SELECT relname, attname, * FROM pg_class c JOIN pg_attribute a on a.attrelid = c.oid WHERE (c.oid = 20431 AND a.attnum = 2) OR (c.oid = 19683 AND a.attnum = 2)
```

**Comment by NeuralGlue** [comment]
The query returned 0 rows. 

Also, the user reports that they drop and recreate tables as part of their import script. I have explained the difference between dropping indexes while importing data versus dropping tables.

Thank you for your assistance.

**Comment by rjuju** [comment]
Thanks for the feedback.  That's still a problem, so I'll add an issue for this.
