### ISSUE TITLE
Option to export to csv all queries instead of current display page (25 queries)

### ISSUE THREAD

**Issue by jdeshayes** [dalibo/powa-web#36]
Option to export to csv all queries instead of current display page (25 queries)

**Comment by rjuju** [comment]
Thanks for the report, we'll fix it asap!

**Comment by rjuju** [comment]
After some more thoughts on this, I wonder if only exporting the current display (25 queries or less if some filters have been applied) is actually useful.

What do you think about always exporting all the data?

**Comment by frost242** [comment]
+1 for exporting all data

**Comment by rjuju** [comment]
Given feedback provided on this issue, I changed the export button to always export all data in a8a113f027e639182e74154a18c0325809568755.

Thanks!
