### ISSUE TITLE
Powa : index suggestion issue 

### ISSUE THREAD

**Issue by palabre** [dalibo/powa-web#41]
Hi 

I am having issue with powa 3.1.1.  when trying to optimize my postgresql database

When I click on the Predicates TAB I have just following messages

An error occured while loading this widget
No quals found for this query

And then no suggestion for any index

Can you help

regards

**Comment by rjuju** [comment]
Hi,

Can you provide the query text and the underlying tables definition?

**Comment by palabre** [comment]
Hi Sure

table definition

mydb=# \d mytab
     Table "public.mytab"
 Column |  Type   | Modifiers
--------+---------+-----------
 id     | integer |
 val    | text    |

mydb=#

query text

select * from mytab where id=?;

regards

**Comment by rjuju** [comment]
I see.  I think the problem is that you ran this query only a few times, and by default pg_qualstats will sample only 1% of the queries.  So you need  to configure `pg_qualstats.sample = 1` if you have a high low tps rate.

**Comment by palabre** [comment]
Hi do you mean in the postgresql.conf file
I added the line pg_qualstats.sample = 1
but still the same still getting  following : 
An error occured while loading this widget

where can I find powa log files?

regards

**Comment by rjuju** [comment]
Ah sorry I meant `sample_rate`.  You also need to reload the configuration and run your query afterward.

For the logs, it depends on how you start powa-web.  Powa-web will output it's log on it's standard output, the caller should redirect the logs.

**Comment by palabre** [comment]
Hi 

It works with  pg_qualstats.sample_rate = 1

in the postgresql.conf file

Thanks for your help

Regards

**Comment by rjuju** [comment]
Good news!

Thanks.
