### ISSUE TITLE
add "catagory" column to PostgreSQL settings display 

### ISSUE THREAD

**Issue by dacresni** [dalibo/powa-web#42]
add catagory to PgSettingsMetricGroup grid to allow sorting of settings by category instead of alphabet.

**Comment by rjuju** [comment]
That's indeed a good idea, thanks!  I'll add it.

**Comment by rjuju** [comment]
That's done in 7c719736f3a1b788d85e40fabda6e8565b5cd421.  I hope I'll at least cherry pick some of the patches proposed by @pgiraud in #33 soon, the grid starts to be very ugly.

Can you confirm that's what you wanted?
