### ISSUE TITLE
No data shown in postgres10

### ISSUE THREAD

**Issue by asr1901** [dalibo/powa-web#43]
Installed powa, powa-web, all needed extensions.  Added powa to pg_hba.conf

When I open powa in the web browser, it simply says "No data available."  None of the databases on the server appear.  I've checked the postgres log for any failed connections or missing db, but there are no errors there.

**Comment by asr1901** [comment]
Extensions | Extension available | Extension installed | Extension sampled | Extension version
-- | -- | -- | -- | --
hypopg | ✓ | ✓ | ✗ | 1.1.0
pg_qualstats | ✓ | ✓ | ✓ | 1.0.3
pg_stat_kcache | ✓ | ✓ | ✓ | 2.0.3
pg_stat_statements | ✓ | ✓ | ✓ | 1.5
pg_track_settings | ✓ | ✓ | ✓ | 1.0.0
powa | ✓ | ✓ | ✗ | 3.1.1

**Comment by rjuju** [comment]
The setup looks ok.  Did you add some configuration for powa (like powa.frequency) or is it all default?

Also, on the main screen you'll only see databases where queries had been run across at least two snapshots (so after 10 minutes by default) on the selected interval (by default last hour).  Was there enough activity on the server?

**Comment by asr1901** [comment]
All settings are default.  This is a fresh postgres10 install with two databases (powa and my testing db).  I've been tuning one particular query that takes ~30 seconds and running this query at least 4 times per hour.  The only custom setting I've done is:
pg_qualstats.sample_rate = 1

Is there any way to force PoWA to show some data or change the sample to force it to look at this query?  Currently everything says "No data" even after 3 hours of testing this query?

**Comment by asr1901** [comment]
Also, whenever I change the window to anything besides the default (past 1 hour), the "waiting" indicator just grinds indefinitely and never completes.

**Comment by rjuju** [comment]
> Is there any way to force PoWA to show some data or change the sample to force it to look at this query? Currently everything says "No data" even after 3 hours of testing this query?

Unfortunately no, it relies on the query being run, and computed by pg_stat_statements and so on.

Is there any error on the database side?  Can you return the results of these queries:

```sql
SELECT * FROM powa_statements;
SELECT * FROM powa_statements_history_current;
SELECT * FROM powa_statements_history;
```

**Comment by asr1901** [comment]
In the powa database, the first two return quite a bit of data.  The last one returns 0 rows.

In my test database where I am running queries, all queries return 0 rows.

**Comment by rjuju** [comment]
Ok, so that means data is sampled and stored, so the UI should display informations.  If there's no error on db side, is there any error on powa-web output?

**Comment by asr1901** [comment]
Unfortunately not, this is the only output I see in powa-web:
[I 171025 11:31:50 powa-web:12] Starting powa-web on http://0.0.0.0:8888
[I 171025 14:04:58 web:1907] 200 GET /overview/ (192.168.110.61) 96.94ms
[I 171025 14:04:59 web:1907] 200 GET /static/css/powa-all.min.css?v=1694496eef7db58c60f5e7e6f1084b6e (192.168.110.61) 53.05ms
[I 171025 14:04:59 web:1907] 200 GET /static/js/require.js?v=640929dac3c23a448d2eebc37bc32062 (192.168.110.61) 31.79ms
[I 171025 14:04:59 web:1907] 200 GET /static/img/favicon/favicon-32x32.png?v=f64009832088abf024bd5c01c175449f (192.168.110.61) 1.28ms
[I 171025 14:04:59 web:1907] 200 GET /static/img/favicon/favicon.ico?v=54c296373bd18377f85203e1bfa886df (192.168.110.61) 1.59ms
[I 171025 14:04:59 web:1907] 200 GET /static/js/powa.min-all.js?v=a8cf39d38f038ea8510dca96753896eb (192.168.110.61) 91.07ms
[I 171025 14:04:59 web:1907] 200 GET /metrics/databases_globals/?from=2017-10-25+13%3A08%3A26-0400&to=2017-10-25+14%3A08%3A26-0400 (192.168.110.61) 74.48ms
[I 171025 14:04:59 web:1907] 200 GET /metrics/by_databases/?from=2017-10-25+13%3A08%3A26-0400&to=2017-10-25+14%3A08%3A26-0400 (192.168.110.61) 57.74ms
[I 171025 14:09:29 web:1907] 200 GET /metrics/databases_globals/?from=2017-10-24+14%3A08%3A26-0400&to=2017-10-25+14%3A08%3A26-0400 (192.168.110.61) 75.52ms
[I 171025 14:09:30 web:1907] 200 GET /metrics/by_databases/?from=2017-10-24+14%3A08%3A26-0400&to=2017-10-25+14%3A08%3A26-0400 (192.168.110.61) 53.63ms

Are there additional logs?  No errors in postgres log either.

**Comment by rjuju** [comment]
Following query should give you on overview of what's stored in powa catalog:

```sql
with src as (select *, (record).* from powa_statements_history_current)
select ts, datname, count(*)
from src
join pg_database d on src.dbid = d.oid
group by 1,2
order by 1,2;
```

**Comment by rjuju** [comment]
No, the only log from powa-web is the one you just showed.

**Comment by asr1901** [comment]
yes on the powa database, the query that starts with (with...) shows me 162 rows.  however, none show up in the web interface

**Comment by rjuju** [comment]
Does some of the reported timestamps (ts column) intersects with the interval on the UI? If yes, the queries should be displayed :/

What version of powa-web are you using? And how did you install it (pip, package...).  What are the versions of sqlalchemy, tornado and psycopg2?

Is there any js error reported by the browser?

**Comment by asr1901** [comment]
I am not able to get it to show any custom interval unfortunately.  Changing the interval just shows the "circular" waiting icon indefinitely.  

Powa-web was installed via yum (yum --enablerepo=pgdg10 install powa_10-web ) .  As far as the other items mentioned, I didn't explicitly install any of those.

**Comment by rjuju** [comment]
Ok.  I'll setup a cento7 to try to reproduce this issue.

**Comment by rjuju** [comment]
I just setup the same environment as you:
```
[root@centos7 ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 

[root@centos7 ~]# rpm -qa |egrep "(postgres|powa)"
powa_10-3.1.1-1.rhel7.x86_64
postgresql10-devel-10.0-1PGDG.rhel7.x86_64
powa_10-web-3.1.1-1.rhel7.x86_64
postgresql10-libs-10.0-1PGDG.rhel7.x86_64
postgresql10-10.0-1PGDG.rhel7.x86_64
postgresql10-contrib-10.0-1PGDG.rhel7.x86_64
postgresql10-debuginfo-10.0-1PGDG.rhel7.x86_64
postgresql10-server-10.0-1PGDG.rhel7.x86_64

[root@centos7 ~]# cat /etc/powa-web.conf
servers={
  'main': {
    'host': '127.0.0.1',
    'port': '5432',
    'database': 'powa',
    'query': {'client_encoding': 'utf8'}
  }
}
cookie_secret="SUPERSECRET_THAT_YOU_SHOULD_CHANGE"

powa-# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description                        
--------------------+---------+------------+-----------------------------------------------------------
 btree_gist         | 1.5     | public     | support for indexing common datatypes in GiST
 pg_qualstats       | 1.0.3   | public     | An extension collecting statistics about quals
 pg_stat_kcache     | 2.0.3   | public     | Kernel statistics gathering
 pg_stat_statements | 1.5     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 powa               | 3.1.1   | public     | PostgreSQL Workload Analyser-core
(6 rows)

[root@centos7 ~]# /usr/bin/powa-web 
[I 171026 07:25:22 powa-web:12] Starting powa-web on http://0.0.0.0:8888
[...]
```

I simulated some activity with pgbench, and the UI works as intended :/

Do you see something different from your setup?

**Comment by asr1901** [comment]
postgres@postgres10:~ $ cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
postgres@postgres10:~ $ rpm -qa | egrep "(postgres|powa)"
postgresql10-10.0-1PGDG.rhel7.x86_64
powa_10-3.1.1-1.rhel7.x86_64
postgresql10-contrib-10.0-1PGDG.rhel7.x86_64
postgresql10-libs-10.0-1PGDG.rhel7.x86_64
postgresql10-devel-10.0-1PGDG.rhel7.x86_64
postgresql10-server-10.0-1PGDG.rhel7.x86_64
powa_10-web-3.1.1-1.rhel7.x86_64
postgres@postgres10:~ $ cat /etc/powa-web.conf
servers={
  'main': {
    'host': 'localhost',
    'port': '5432',
    'database': 'povodyrev2',
    'query': {'client_encoding': 'utf8'}
  }
}
cookie_secret="AAA"
postgres@postgres10:~ $ psql -d powa
psql (10.0)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

powa=# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description                        
--------------------+---------+------------+-----------------------------------------------------------
 btree_gist         | 1.5     | public     | support for indexing common datatypes in GiST
 hypopg             | 1.1.0   | public     | Hypothetical indexes for PostgreSQL
 pg_qualstats       | 1.0.3   | public     | An extension collecting statistics about quals
 pg_stat_kcache     | 2.0.3   | public     | Kernel statistics gathering
 pg_stat_statements | 1.5     | public     | track execution statistics of all SQL statements executed
 pg_track_settings  | 1.0.0   | public     | Track settings changes
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
 powa               | 3.1.1   | public     | PostgreSQL Workload Analyser-core
(8 rows)

powa=# \q

**Comment by asr1901** [comment]
Going to install the other yum repos that you have and see if I get a different result

**Comment by rjuju** [comment]
> postgres@postgres10:~ $ cat /etc/powa-web.conf
> [...]
>     'database': 'test2',

I think this is your issue.  database must be where you installed the powa extension, accordingly to powa.database setting.  The UI will connect to any database on your server as needed.

However you shouldn't be able to connect if this powa isn't installed in the configured database.  Did you install powa in this database too?

**Comment by asr1901** [comment]
Yes I did install it there as well, but I noticed that all of the powa data is in the powa database.  I think a database named 'powa' has to be hardcoded, because I only created a database called 'powa' because it was showing me errors in the postgres log.  I am going to change my db in the web-conf to powa and see if that fixes it.

**Comment by asr1901** [comment]
OK, changing it to powa fixed it and I do see data now.

**Comment by rjuju** [comment]
Ok good!

The give some explanations, powa will store all informations (pg_stat_statements, pg_qualstats...) in only one place, whatever database was the query played.  It's better to have a dedicated database for that, so by default the powa database is used.  You can configure it with powa.database in postgresql.conf if needed.

You can therefore drop powa extension in any database except powa.

**Comment by asr1901** [comment]
Thank you so much for your help, it is truly appreciated.  Glad to get this working with pg10.  It looks like my issue ended up being that powa.database was different than the db name in /etc/powa-web.conf

**Comment by rjuju** [comment]
Thanks for the feedback :)

I'll try to see if documentation can be improved about this parameter, and general architecture.
