### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by indreek** [dalibo/powa-web#7]
When installing powe-web it fails with error: 
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mbb6R4-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/psycopg2
Storing debug log for failure in /root/.pip/pip.log

powa-web dependency is psycopg2 and for psycopg2 dependency is python-dev. You need to install it before powa-web to succeed.

Indrek

**Comment by indreek** [comment]
I was installing according to http://powa.readthedocs.org/en/latest/quickstart.html

**Comment by rjuju** [comment]
Hello,

indeed the python development packages are required to compile some of the dependancies. I'll update the documentation.

If you didn't solve the problem yet, you should do either : 

    apt-get install python-dev

or

    yum install python-devel

depending if you're using debian/ubuntu or RHEL/Centos.

Regards.

**Comment by rjuju** [comment]
Documentation updated in commit https://github.com/dalibo/powa/commit/c5d2a9ee6090936f8a63fc1db6c9a06f9f60506c.
