### ISSUE TITLE
Unable to login, failed with "Auth failed"

### ISSUE THREAD

**Issue by grebois** [dalibo/powa-web#8]
I'm trying to login with a superuser, changed the password to be sure, and still I'm getting;

![screen shot 2015-11-16 at 11 33 44](https://cloud.githubusercontent.com/assets/1569751/11179771/109154a4-8c56-11e5-9194-1840dd7122ba.png)

**Comment by grebois** [comment]
Fixed, the problem was in pg_hba.conf

[E 151116 11:42:03 user:20] (OperationalError) FATAL:  no pg_hba.conf entry for host "::1"

**Comment by kvnema** [comment]
Same error , not resolved by making entry for ::1

Below are the entries in pg_hba.conf :+1: 

local   all             postgres                                md5
host    all             postgres        127.0.0.1/32            md5
host    all             postgres        ::1/128                 md5
host    replication     postgres        127.0.0.1/32            md5
host    all             postgres        127.0.0.1/32            md5
host    all             postgres        0.0.0.0/0               reject
host    all             postgres        ::/0                    reject
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5
host    all             all             ::/1                    md5
host    all             all             ::1/0                   md5
